// Alert type constants
module.exports = {
  SIGNAL_UPDATE:  "SIGNAL_UPDATE",
  HEATMAP_UPDATE: "HEATMAP_UPDATE",
  REGIME_UPDATE:  "REGIME_UPDATE",
  SCANNER_UPDATE: "SCANNER_UPDATE",
  HEALTH_UPDATE:  "HEALTH_UPDATE",
  KILL_SWITCH:    "KILL_SWITCH"
};
